In [1]:
import numpy as np
np.random.seed(4)
m=60
w1,w2 = 0.1,0.3
noise=0.1

angles = np.random.rand(m) * 3 * np.pi /2 -0.5
X=np.empty((m,3))
X[:,0] = np.cos(angles) + np.sin(angles)/2 + noise *np.random.randn(m) /2
X[:,1] = np.sin(angles) * 0.7 + noise * np.random.randn(m) /2
X[:,2] = X[:,0] * w1 + X[:,1] * w2 + noise * np.random.randn(m)

In [2]:
X_centered = X - X.mean(axis=0)
U,s,Vt = np.linalg.svd(X_centered)

In [3]:
c1 = Vt.T[:,0]
c2 = Vt.T[:,1]

In [4]:
c1

array([0.93636116, 0.29854881, 0.18465208])

In [5]:
c2

array([-0.34027485,  0.90119108,  0.2684542 ])

In [6]:
m,n = X.shape

S=np.zeros(X_centered.shape)
S[:n,:n] = np.diag(s)

In [7]:
np.allclose(X_centered,U.dot(S).dot(Vt))

True

In [8]:
W2=Vt.T[:,:2]
X2D = X_centered.dot(W2)

In [9]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X2D=pca.fit_transform(X)

In [10]:
pca.components_

array([[-0.93636116, -0.29854881, -0.18465208],
       [ 0.34027485, -0.90119108, -0.2684542 ]])

In [11]:
pca.explained_variance_ratio_

array([0.84248607, 0.14631839])

In [12]:
pca=PCA()
pca.fit(X)
cumsum=np.cumsum(pca.explained_variance_ratio_)
d=np.argmax(cumsum>=0.95)+1

In [13]:
d

2

In [14]:
pca=PCA(n_components=0.95)

In [15]:
X_reduced=pca.fit_transform(X)

In [16]:
X_reduced.shape

(60, 2)

In [17]:
from sklearn.datasets import fetch_mldata
mnist = fetch_mldata('MNIST original')

C:\tcl\Anaconda\envs\py3\lib\site-packages\sklearn\utils\deprecation.py:77: DeprecationWarning: Function fetch_mldata is deprecated; fetch_mldata was deprecated in version 0.20 and will be removed in version 0.22
  warnings.warn(msg, category=DeprecationWarning)
C:\tcl\Anaconda\envs\py3\lib\site-packages\sklearn\utils\deprecation.py:77: DeprecationWarning: Function mldata_filename is deprecated; mldata_filename was deprecated in version 0.20 and will be removed in version 0.22
  warnings.warn(msg, category=DeprecationWarning)


In [18]:
from sklearn.model_selection import train_test_split
X=mnist['data']
y=mnist['target']
X_train,X_test,y_train,y_test = train_test_split(X,y)

In [20]:
from sklearn.decomposition import IncrementalPCA
n_batches=100
inc_pca=IncrementalPCA(n_components=154)
for X_batch in np.array_split(X_train,n_batches):
    print('.',end='')
    inc_pca.partial_fit(X_batch)
X_reduced = inc_pca.transform(X_train)

....................................................................................................

In [ ]:
# from sklearn.decomposition import KernelPCA

# rbf_pca=KernelPCA(n_components=2,kernel='rbf',gamma=0.04)
# X_reduced = rbf_pca.fit_transform(X_train)